[format.rules]
indent-width = 4
line-width = 80

[lint.rules]
tables-out-of-order = "error"

[[schemas]]
path = "tombi://json.schemastore.org/pyproject.json"
include = ["pyproject.toml"]

format.rules = {
    array-values-order.enabled = false,
    table-keys-order.enabled = false,
}

overrides = [
    {
        targets = [
            "project.dependencies",
            "project.authors",
            "project.scripts",
            "dependency-groups.*",
            "tool.ruff.lint.*",
            "tool.ruff.lint.pep8-naming.*",
            "tool.ruff.lint.per-file-ignores",
            "tool.ruff.lint.per-file-ignores.*",
        ],
        format.rules = {
            array-values-order = "version-sort",
            table-keys-order = "ascending",
        }
    },
]
